---
 - hosts: mhost1
   gather_facts: False
   vars:
        dict:
           key1: value1
           key2: value2
   tasks:
        - name: Displaying variable value
          debug:
               msg: "{{ dict }}"
